apiVersion: v2
appVersion: "1.0"
description: Chart to test dependencies
home: https://github.com/helm/charts-repo-actions-demo
maintainers:
  - email: email@example.com
    name: Name
name: dependencies-v2
sources:
  - https://github.com/helm/charts-repo-actions-demo
version: 0.1.5
dependencies:
  - name: redis
    version: 10.5.13
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
